### ISSUE TITLE
Unrelated thread can cause Awaitility to throw an exception

### ISSUE THREAD

**Issue by dotstone** [awaitility/awaitility#120]
Awaitility sets its own UncaughtExceptionHandler globally (ConditionAwaiter:49), i.e. *all* spawning threads are affected. This is pretty risky and can lead to many problems, one of them being:

During an awaitility until() call, if a new thread spawns and throws an exception, the exception handler for the awaitility call catches that exception and stores it assuming the exception was caused by the awaitility callable -> the awaitility call fails (eventually even before executing the callable).

Reproducer:
```
@Test
public void test() {
    new Thread(() -> {
        try {
            Thread.sleep(100);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        new Thread(() -> {
            throw new RuntimeException("Some irrelevant exception");
        }).start();
    }).start();
    Awaitility.await()
        .pollDelay(500, TimeUnit.MILLISECONDS)
        .until(() -> true);
}
```
will fail with 
```
java.lang.RuntimeException: Some irrelevant exception

	at com.dynatrace.oneagent.atf.common.AwaitilityReproducer.lambda$null$0(AwaitilityReproducer.java:20)
	at java.lang.Thread.run(Thread.java:748)
```
Tested with versions 1.7 and 3.1.2

**Comment by johanhaleby** [comment]
This is by design, see docs [here](https://github.com/awaitility/awaitility/wiki/Usage#example-12---ignoring-uncaught-exceptions).

**Comment by dotstone** [comment]
So there's no plan to change that behavior? In our environment, we are frequently running into that problem with Awaitility calls that take several hundred milliseconds. We can't remove the UncaughtExceptionHandler as we need to catch exception from the callables. The only alternative I see is to use `pollInSameThread` which has its own downsides.

**Comment by dotstone** [comment]
I just noticed that `dontCatchUncaughtExceptions` refers to exceptions in *other* threads only. So problem solved. Sorry for my misunderstanding.
IMHO it can be quite misleading to turn on that feature by default (I see there was already a discussion here: https://github.com/awaitility/awaitility/issues/119). We had to invest several hours of debugging just to find out that the exception was re-thrown by Awaitility as the stacktrace doesn't reflect that (maybe wrapping the exception would be a good idea)

**Comment by johanhaleby** [comment]
@dotstone May be something to reconsider now that two people have experienced issues with this in a short period of time. Thanks the feedback.

**Comment by Darkvater** [comment]
Ugh, I spent a whole day and a half tracking this down! It made it all the more tricky as things were failing from a cucumber test which does some magic with the stack trace so I would get a stack trace of a wholly unrelated exception into my cucumber steps. Anyways:

I second doing something with this. The wiki docs mentioning it are not enough, this needs a big fat warning! If I might suggest a solution: it looks like the uncaughtThroeabke is thrown in ConditionAwaiter. Is it possible to wrap it in an Awaitility exception type which:
1. At least make it clear where the exception is coming from to fail the test
2. (for bonus points) would include some description how this exception came to be and what can de done to change the behaviour (e.g. turn off)
