### ISSUE TITLE
Thread.sleep may be interrupted

### ISSUE THREAD

**Issue by ben-manes** [awaitility/awaitility#134]
https://github.com/awaitility/awaitility/blob/8a33d4805d115c489fb914f9372e3ff36a0cbf7b/awaitility/src/main/java/org/awaitility/core/ConditionAwaiter.java#L81-L83

When trying out G1's `-XX:+UseStringDeduplication` to reduce string memory bloat in my unit test reporter, I receive `InterruptedException`. The sleeper does not handle that case, though it is well documented. Perhaps consider implementing something like Guava's [Uninterruptibles#sleepUninterruptibly](https://github.com/google/guava/blob/bf9e8fa954bd76fd6642445fa644c729f91f30f2/guava/src/com/google/common/util/concurrent/Uninterruptibles.java#L382-L402) instead?

```
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:82)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:79)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:27)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:902)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:860)
	at com.github.benmanes.caffeine.cache.IsValidBoundedLocalCache.checkReadBuffer(IsValidBoundedLocalCache.java:89)
```

**Comment by johanhaleby** [comment]
Oh nice find! Maybe we can borrow some code from guava.

**Comment by johanhaleby** [comment]
I've now fixed this.

**Comment by ben-manes** [comment]
Thanks!

**Comment by ben-manes** [comment]
Can you also put the interrupt waiting logic to handle futures? The exception below seems like an easy fix, as Guava's `Uninterruptibles` includes future variants that you could copy. 

Like last time, I'm trying out TestNG 7.0 which I can't upgrade to because of its increased its memory usage. That puts a lot more pressure on the GC and I run a lot of tests. The GC pause causes an interrupt, I guess.

```
Caused by: java.lang.InterruptedException
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
	at java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:93)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:816)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:785)
```

**Comment by johanhaleby** [comment]
Fixed by copying some additional methods from Guava. I've published a new snapshot and you can try it out by adding this repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

then depend on version `4.0.0-rc2-SNAPSHOT`.

**Comment by ben-manes** [comment]
closer, but another one to get:
```
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1475)
	at java.util.concurrent.Executors$DelegatedExecutorService.awaitTermination(Executors.java:675)
	at org.awaitility.core.ExecutorLifecycle.lambda$normalCleanupBehavior$2(ExecutorLifecycle.java:75)
	at org.awaitility.core.EvaluationCleanup.executeNormalCleanupBehavior(EvaluationCleanup.java:46)
	at org.awaitility.core.ExecutorLifecycle.executeNormalCleanupBehavior(ExecutorLifecycle.java:58)
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:158)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:873)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:842)
	at com.github.benmanes.caffeine.cache.IsValidBoundedLocalCache.checkReadBuffer(IsValidBoundedLocalCache.java:88)
	at com.github.benmanes.caffeine.cache.IsValidBoundedLocalCache.matchesSafely(IsValidBoundedLocalCache.java:68)
	at com.github.benmanes.caffeine.cache.IsValidCache.matchesSafely(IsValidCache.java:57)
	at com.github.benmanes.caffeine.cache.IsValidCache.matchesSafely(IsValidCache.java:34)
	at org.hamcrest.TypeSafeDiagnosingMatcher.matches(TypeSafeDiagnosingMatcher.java:57)
	at org.hamcrest.core.Is.matches(Is.java:25)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:10)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at com.github.benmanes.caffeine.cache.testing.CacheValidationListener.validate(CacheValidationListener.java:89)
	at com.github.benmanes.caffeine.cache.testing.CacheValidationListener.afterInvocation(CacheValidationListener.java:67)
	... 13 more
```

**Comment by johanhaleby** [comment]
I've tried to fix this, although I couldn't simply copy code from Guava now so I'm not sure if it actually works. Published a new snapshot! Can you think of a test case that I can use to verify that the uninterruptible stuff is actually working?

**Comment by ben-manes** [comment]
You would have one thread waiting on a condition and then call `Thread.interrupt()` on another thread. You might look at Guava's test code for Uninterruptibles, which does these types of things.

For my tests, the following command runs 323k tests fine on TestNG 6.14.3 in about 2 minutes.
```gradle
./gradlew :caffeine:strongKeysAndStrongValuesAsyncCaffeineTest
```

It fals as shown with 7.0.0, as reported in https://github.com/cbeust/testng/issues/2096. I have tried to reduce memory usage on my side, but the cause is in their report handling. This triggers full GCs and increases the execution time to 4 minutes. However thanks to your fixes it now passes rather than having test failures. I don't know when/if I can upgrade testng in this state, but that's not your problem and I have to work it out with them.

You can play with this [patch](https://github.com/awaitility/awaitility/files/3513414/testng.patch.txt) if interested.
