### ISSUE TITLE
atLeast/during not enforced unless until is declared

### ISSUE THREAD

**Issue by DerGreco** [awaitility/awaitility#229]
This won't work, I don't know if it doesn't go with the spirit of the library, but I was expecting so.

```java
Instant start = Instant.now();
    await().during(Duration.ofMillis(250))
//        .until(() -> true)
    ;
    logger.info("Awaited {}", Duration.between(start, Instant.now()));
```

![image](https://user-images.githubusercontent.com/2787749/147746145-ccb7fff1-5647-4b6f-94af-cc7d4fad3780.png)

**Comment by DerGreco** [comment]
Also, with atLeast(500).until(true) the following exception can be thrown, which makes no apparent sense reading the sentence literally. You await at least X until the condition is true, and if the condition is true, you await at least X, is what I would expect.

`org.awaitility.core.ConditionTimeoutException: Condition was evaluated in 100 milliseconds which is earlier than expected minimum timeout 500 milliseconds
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:169)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:908)
`

**Comment by GChapel** [comment]
Hello,

About your first post, you can specify **pollInterval** to reach your needs :
```java
@Test
public void differentPollIntervalTest() {

    List<Duration> pollIntervalDurationList =
        List.of(
            Duration.ofMillis(100), // i.e. default pollInterval
            Duration.ofMillis(1),   // Extremely fast ( /!\ cpu usage )
            Duration.ofMillis(1000) // Slow
            );

    for (Duration duration : pollIntervalDurationList) {
        long totalDuration = 0;
        for (int i = 0; i < 10; i++) {
        long start = System.currentTimeMillis();
        await().during(Duration.ofMillis(250)).pollInterval(duration).until(() -> true);
        totalDuration += (System.currentTimeMillis() - start);
        }

        System.out.println(
            String.format("pollInterval %s : %d ms avg", duration, totalDuration / 10));
    }
}
```

Here the result : 

> pollInterval PT0.1S : 439 ms avg
pollInterval PT0.001S : 255 ms avg
pollInterval PT1S : 2024 ms avg


You can also set **pollDelay** to delay the start of polls.

Regards,
