### ISSUE TITLE
JavaVersionDetector class fails with NumberFormatException on Temurin JDK 23 EA builds

### ISSUE THREAD

**Issue by jerboaa** [awaitility/awaitility#277]
The JavaVersionDetector class fails on specific version strings that `java.version` property can hold. In this case it's `23-beta`, which results in:

```
Caused by: java.lang.NumberFormatException: For input string: "23-beta"
	at java.base@23-beta/java.lang.Integer.parseInt(Integer.java:588)
	at java.base@23-beta/java.lang.Integer.parseInt(Integer.java:685)
	at org.awaitility.core.JavaVersionDetector.getJavaMajorVersion(JavaVersionDetector.java:21)
	at org.awaitility.core.LambdaErrorMessageGenerator.getLambdaDetectionClassName(LambdaErrorMessageGenerator.java:86)
	at org.awaitility.core.LambdaErrorMessageGenerator.isLambdaClass(LambdaErrorMessageGenerator.java:30)
	at org.awaitility.core.AssertionCondition.generateDescriptionPrefix(AssertionCondition.java:87)
	at org.awaitility.core.AssertionCondition.getMatchMessage(AssertionCondition.java:73)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:54)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
```

Consider using the `Runtime.Version` API which is available for JDK 11+

```
jshell> var v = Runtime.getRuntime().version();
v ==> 23-beta+14-ea

jshell> v.feature()
$3 ==> 23
```

**Steps to reproduce:**
1. Download a JDK 23 EA build from Adoptium. Example here: https://adoptium.net/temurin/nightly/?version=23
2. Run `JavaVersionDetector.getJavaMajorVersion()` on it.
3. Observe `NumberFormatException`

**Aditional Info:**
The existing code seems to not account for the `-` in `23-beta`. See:
https://github.com/awaitility/awaitility/blob/fbe16add874b4260dd240108304d5c0be84eabc8/awaitility/src/main/java/org/awaitility/core/JavaVersionDetector.java#L6-L22

**Comment by manoj2411** [comment]
Got similar error with our CI/CD pileline `java.lang.NumberFormatException: For input string: "17-ea"`

**Comment by estekhin** [comment]
Bumping minimum Java version from the current 1.8 to at least 9 (better yet, 11 as "lts") will provide access to `Runtime.version()` which will remove the need to parse the string.
