### ISSUE TITLE
Fails prematurely due to miscalculated elapsed time

### ISSUE THREAD

**Issue by mjiderhamn** [awaitility/awaitility#281]
Please look at the timestams and the message in this log

```
2024-04-30T13:21:22.8890775Z [INFO] Running foo.Bar
2024-04-30T13:21:23.0238921Z 13:16:17 INFO  [foo.Bar] (main) Starting evaluation
2024-04-30T13:21:23.0575168Z 13:16:22 INFO  [foo.Bar] (main) Condition foo.Bar$$Lambda/0x00007f344253f6d8 was not fulfilled within 5 seconds.
2024-04-30T13:21:23.1000272Z 13:16:23 INFO  [foo.Bar] (awaitility-thread) Callable condition returned false (elapsed time 6100 milliseconds, remaining time -1100 milliseconds (last poll interval was 100 milliseconds))
```

As can be seen, Awaitility claims to have waited 6100 ms while the clock has ticked some ~76 ms.

Have so far only been able recreate this running as a GitHub Action, where however it seems consistent.

Stacktrace:
```
2024-04-30T13:21:23.1002692Z org.awaitility.core.ConditionTimeoutException: Condition foo.Bar$$Lambda/0x00007f344253f6d8 was not fulfilled within 5 seconds.
2024-04-30T13:21:23.1003061Z 	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
2024-04-30T13:21:23.1003362Z 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
2024-04-30T13:21:23.1003651Z 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
2024-04-30T13:21:23.1003935Z 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
2024-04-30T13:21:23.1004219Z 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
...
2024-04-30T13:21:23.1008130Z Caused by: java.util.concurrent.TimeoutException
2024-04-30T13:21:23.1008400Z 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
2024-04-30T13:21:23.1008762Z 	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)
2024-04-30T13:21:23.1009123Z 	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)
2024-04-30T13:21:23.1009402Z 	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:103)
2024-04-30T13:21:23.1009501Z 	... 14 more
```

Please advice how to debug further.

**Comment by mjiderhamn** [comment]
Noticed the dual timestamps and need to investigate more what's going on in GitHub Action. Sometime time differs by several minutes.
