### ISSUE TITLE
JavaVersionDetector throws NumberFormatException in EA versions of Java due to -ea suffix

### ISSUE THREAD

**Issue by gjwatts** [awaitility/awaitility#284]
In the pre-GA builds of Java 23, they appended `-ea` to the Java version that gets reported back in `System.getProperty("java.version")`.  When that happens, a `NumberFormatException` is thrown in [JavaVersionDetector](https://github.com/awaitility/awaitility/blob/master/awaitility/src/main/java/org/awaitility/core/JavaVersionDetector.java#L4) because the `-ea` part cannot be turned into a number.

When we run our testing, we hit stacktraces that look like this:
```
testCancelWithoutInterrupt_EE10_FEATURES_MicroProfile_70:java.lang.NumberFormatException: For input string: "23-ea"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:588)
at java.base/java.lang.Integer.parseInt(Integer.java:685)
at org.awaitility.core.JavaVersionDetector.getJavaMajorVersion(JavaVersionDetector.java:21)
at org.awaitility.core.LambdaErrorMessageGenerator.getLambdaDetectionClassName(LambdaErrorMessageGenerator.java:86)
at org.awaitility.core.LambdaErrorMessageGenerator.isLambdaClass(LambdaErrorMessageGenerator.java:30)
at org.awaitility.core.CallableHamcrestCondition.getCallableDescription(CallableHamcrestCondition.java:51)
at org.awaitility.core.AbstractHamcrestCondition.getMatchMessage(AbstractHamcrestCondition.java:68)
at org.awaitility.core.AbstractHamcrestCondition.lambda$new$0(AbstractHamcrestCondition.java:51)
at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
```

Would you please fix JavaVersionDetector.java to handle the `-ea` suffix or other non-numeric characters?

**Comment by snicoll** [comment]
Duplicates #277, #275.
