### ISSUE TITLE
Cannot test with jdk 24-ea version

### ISSUE THREAD

**Issue by olamy** [awaitility/awaitility#287]
We (the Jetty project) are trying to test jdk 24 (ea version). 
But it looks to not being supported by awaitility

Error 
```
[ERROR] org.eclipse.jetty.util.ConcurrentPoolTest.testLeakReserved(Factory)[4] -- Time elapsed: 0.148 s <<< ERROR!

java.lang.NumberFormatException: For input string: "24-ea"

	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)

	at java.base/java.lang.Integer.parseInt(Integer.java:563)

	at java.base/java.lang.Integer.parseInt(Integer.java:660)

	at org.awaitility.core.JavaVersionDetector.getJavaMajorVersion(JavaVersionDetector.java:21)

	at org.awaitility.core.LambdaErrorMessageGenerator.getLambdaDetectionClassName(LambdaErrorMessageGenerator.java:86)
```

**Comment by awa-xima** [comment]
We're getting the same error, but with `22-ea`. The issue is [org.awaitility.core.JavaVersionDetector#getJavaMajorVersion](https://github.com/awaitility/awaitility/blob/master/awaitility/src/main/java/org/awaitility/core/JavaVersionDetector.java). You should probably also remove everything after dashes (-), not just dots (.)

**Comment by awa-xima** [comment]
Sorry about the last message -- I just noticed this is already fixed. We got the same error, but with `awaitility` 4.2.2, this has been fixed.

**Comment by olamy** [comment]
Already fixed by some changes
