### ISSUE TITLE
how can i use driver() methods in 'until'?

### ISSUE THREAD

**Issue by perkele99** [awaitility/awaitility#288]
when I use the method return WebDriver I get an error

```
Awaitility.await().atMost(Duration.ofSeconds(5))
        .until(() -> driver().getCurrentUrl().contains("selenium"));
```
```
java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.getCurrentUrl()" because the return value of "test.testexecute.TestBankIntegration.driver()" is null

	at test.testexecute.TestBankIntegration.lambda$testBankIntegration1$1(TestBankIntegration.java:44)
	at org.awaitility.core.CallableCondition$ConditionEvaluationWrapper.eval(CallableCondition.java:99)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

when the driver save to a variable then it works correctly

```
WebDriver webDriver = driver();
Awaitility.await().atMost(Duration.ofSeconds(5))
        .until(() -> webDriver.getCurrentUrl().contains("selenium"));
```

how can i use driver() methods in 'until'?

**Comment by johanhaleby** [comment]
I'm guessing here, but maybe WebDriver use some sort of thread local variable? If so, that would explain why you would get the value outside the "until" lambda. You could try [pollInSameThread](https://github.com/awaitility/awaitility/wiki/Usage#thread-handling) and see if that works.
