### ISSUE TITLE
Feature: add last throwable as root cause to ConditionTimeoutException

### ISSUE THREAD

**Issue by lbeuster** [awaitility/awaitility#67]
Having the complete stacktrace of the last assertion failure would make things easier. 

Currently I cannot use something like
```java
await()...(() -> {
    ...
    assertNotNull(var1);
    assertNotNull(var2);
}
```
because the ConditionTimeoutException is the same for both assertions.

Thanks
Lars

**Comment by johanhaleby** [comment]
What stacktrace are you getting?

**Comment by johanhaleby** [comment]
When I try to reproduce I get this:

```java
org.awaitility.core.ConditionTimeoutException: Condition defined as a org.awaitility.AwaitilityJava8Test null within 10 seconds.

	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:103)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:117)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:32)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:809)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:648)
	at org.awaitility.AwaitilityJava8Test.test(AwaitilityJava8Test.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

which means it's a timeout and not an exception that caused the test to fail (since assertNotNull doesn't throw any exception but an error)

**Comment by johanhaleby** [comment]
Sorry for my initial confusion, I've solved this now and published a new snapshot. Please try version `2.0.1-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by lbeuster** [comment]
Yes, much better, thanks ;)
