### ISSUE TITLE
java.util.concurrent.TimeoutException is thrown from `until`

### ISSUE THREAD

**Issue by shtratos** [awaitility/awaitility#97]
I use Awaitility 3.0.0 like this:
```
try {
    Awaitility.await().atMost(FIVE_SECONDS).until(myObject::isReady);
} catch (ConditionTimeoutException e) {
    // handle timeout
}
```

Javadoc says that `ConditionTimeoutException` will be thrown, but sometimes I get Java `TimeoutException` instead:
```
...
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_144]
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:87)
        at org.awaitility.core.CallableCondition.await(CallableCondition.java:79)
        at org.awaitility.core.CallableCondition.await(CallableCondition.java:27)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:840)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:802)
        at ... my code ...
```

Which is thrown from this line:
https://github.com/awaitility/awaitility/blob/010782959f9cd67b5e322ec354b13613e0c45567/awaitility/src/main/java/org/awaitility/core/ConditionAwaiter.java#L87

**Comment by jamesw966** [comment]
A very simple reproduction:

```
try {
    await().atMost(new Duration(1000, TimeUnit.MILLISECONDS)).until(() -> {
        Thread.sleep(5000);
        return false;
    });
} catch (Exception e) {
    System.err.println(e.getClass().getName());
}
```

When the `Thread.sleep` is uncommented, it prints `java.util.concurrent.TimeoutException` to stderr. When that line is commented out, it prints `org.awaitility.core.ConditionTimeoutException`.

**Comment by johanhaleby** [comment]
I've published a snapshot now that should include a fix for this issue (thanks @jamesw966). Please try version `3.0.1-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```
